server {
    listen       80;
    server_name  localhost;
    root   /usr/share/nginx/html;
    index  index.html;

    # 1. Soporte SPA: Cualquier ruta que no sea archivo, va al index
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Health Check: Responder OK siempre para que ECS no nos mate
    location /health {
        access_log off;
        add_header 'Content-Type' 'application/json';
        return 200 '{"status":"alive"}';
    }

    # Configuración de errores
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}